[WIP]Added new commands for namespace - sleep and wake
okteto/okteto pull request #3479
Opened 2023-03-26 17:23 UTC by NitishKumar06

Fixes: #3470

**Note:** This is a WIP PR - the changes applied are running perfectly. However, I believe that code can be improved considering the file _delete.go_. The test cases need to be added as well. I'm raising this PR before hand to make sure we don't keep bunch of suggestions at the end to be implemented all at once rather it's better if suggestions are implemented side by side.

2023-03-27 14:24 UTC, jLopezbarb commented
Code looks good. I tested the branch and everything seems correct. I'll leave it open to see if anyone wants to review it but LGTM

2023-03-27 14:31 UTC, NitishKumar06 commented
Squashed the commits

2023-03-27 17:55 UTC, NitishKumar06 commented
> Thanks @NitishKumar06. The docs should be updated in the https://github.com/okteto/docs. You can create the PR to gather feedback

Yes, I'm aware of it. Just mentioning this here so that anyone who takes a look at this PR and would like to proceed with providing docs can go ahead, otherwise I'd love to do the same.

2023-03-30 08:18 UTC, jLopezbarb requested changes

2023-03-30 08:18 UTC, jLopezbarb commented on cmd/namespace/wake.go
> +			if err := contextCMD.NewContextCommand().Run(ctx, &contextCMD.ContextOptions{}); err != nil {
```suggestion
			if err := contextCMD.NewContextCommand().Run(ctx, &contextCMD.ContextOptions{Namespace: nsToWake, Show: true}); err != nil {
```

2023-03-30 08:18 UTC, jLopezbarb commented on cmd/namespace/sleep.go
> +			if err := contextCMD.NewContextCommand().Run(ctx, &contextCMD.ContextOptions{}); err != nil {
```suggestion
			if err := contextCMD.NewContextCommand().Run(ctx, &contextCMD.ContextOptions{Namespace: nsToSleep, Show: true}); err != nil {
```

2023-03-30 15:30 UTC, NitishKumar06 commented on cmd/namespace/wake.go
> +			if err := contextCMD.NewContextCommand().Run(ctx, &contextCMD.ContextOptions{}); err != nil {
marking as Resolved!

2023-03-30 16:04 UTC, jLopezbarb approved these changes

2023-04-15 11:49 UTC, NitishKumar06 commented
Ping @jLopezbarb

2023-04-17 10:33 UTC, jLopezbarb commented
I'm waiting for the next release to be cut to merge this PR. I already tested it and it works perfect.

2023-04-17 11:11 UTC, NitishKumar06 commented
When is the next release?

2023-04-17 11:15 UTC, jLopezbarb commented
The plan is that every month we do a CLI release, but first we need to test that everything is fine and we do a cut creating a beta release. We'll be ready to cut the beta between today and tomorrow, and after that we can merge this PR

2023-04-17 12:44 UTC, NitishKumar06 commented
> The plan is that every month we do a CLI release, but first we need to test that everything is fine and we do a cut creating a beta release. We'll be ready to cut the beta between today and tomorrow, and after that we can merge this PR

This is amazing! Do you have any suggestions how can I contribute more closely for the next release apart from solving issues?

2023-04-20 08:33 UTC, jLopezbarb commented
> > The plan is that every month we do a CLI release, but first we need to test that everything is fine and we do a cut creating a beta release. We'll be ready to cut the beta between today and tomorrow, and after that we can merge this PR
> 
> This is amazing! Do you have any suggestions how can I contribute more closely for the next release apart from solving issues?

We release a beta one week before doing the official release. We test on that beta that everything is working smoothly. I'll talk with the team to create open that process to the community 😄

2023-04-20 08:35 UTC, jLopezbarb commented
This PR is a game change, at least for me. I'm very glad to merge this feature. Thanks a lot again @NitishKumar06

2023-04-20 08:35 UTC, merged